name: icongen
description: "An AI icon generator"

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.8.1

dependencies:
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  firebase_ai: ^3.4.0
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  firebase_remote_config: ^6.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0-dev.17
  flutter_secure_storage: ^9.2.4
  gal: ^2.3.2
  go_router: 16.2.1
  google_fonts: ^6.3.0
  image: ^4.5.4
  logger: ^2.6.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  share_plus: ^12.0.0


dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true


