// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv1tFTKDSjujaLQRzMCgRuclbKzn9entk',
    appId: '1:966726926985:web:1f50045b9b410b987bbc58',
    messagingSenderId: '966726926985',
    projectId: 'icongen-c5e50',
    authDomain: 'icongen-c5e50.firebaseapp.com',
    storageBucket: 'icongen-c5e50.firebasestorage.app',
    measurementId: 'G-LPZ8LWBZ95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmt9ScjwFNP4T0Zzsy6oBSPR5xgh9SfVw',
    appId: '1:966726926985:android:acb5cc32712300b47bbc58',
    messagingSenderId: '966726926985',
    projectId: 'icongen-c5e50',
    storageBucket: 'icongen-c5e50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDobVSb_0nKZnzT4e2WzPDM1K_B3eXLC1E',
    appId: '1:966726926985:ios:3ef257125e13da5e7bbc58',
    messagingSenderId: '966726926985',
    projectId: 'icongen-c5e50',
    storageBucket: 'icongen-c5e50.firebasestorage.app',
    iosBundleId: 'com.olekslukian.icongen',
  );

}